import "./pages/index.css";
import "./js/script.js";
import "./images/avatar.jpg";
import "./images/close.svg";
import "./images/like-active.svg";
import "./images/like-inactive.svg";
import "./images/loading.gif";
import "./images/logo.svg";
import "./images/trash-icon.svg";